### ISSUE TITLE
Get partial facts if a device is not accessible.

### ISSUE THREAD

**Issue by AJNOURI** [aristanetworks/ansible-cvp#104]
Hey @titom73

Might be related to #95 

Issue Type
------
- Question/feature request

Module Name
------
- facts

OS / Environment
------
- 2018.2.5

Summary
------

We are testing the current modules on an IPFabric lab testbed, but one of the devices has authentication mode changed (through tacacs), so no more available with CVP username/login credentials; which makes the module facts fails with the device MAC.

Is it possible to still get the JSON output for all other devices and mention the ones failed? In case we want to exclude the failed machine from the deployment.

Thanks.

**Comment by titom73** [comment]
Hello

Issue #95 is changing `cv_facts` behavior:
- By default, facts do not collect configuration
- You can explicitely collect this element with an optional keyword.

In the meantime, `cv_facts` extracts configuration from devices with a status set to `"deviceStatus": "STREAMING"` meaning offline devices and 3rd part devices are not collected.

If device is streaming and we can't connect to it to get configuration, we might think about a value like `"CONFIG":"NOT AVAILABLE"`. Is that suitable for you ?

**Comment by AJNOURI** [comment]
Sorry for the late reply,
Yes, "deviceStatus": "STREAMING" looks appropriate.

**Comment by titom73** [comment]
If so, I will move forward and close this case.

For documentation related to facts and how to configure options, please refer to [Project documentation](https://github.com/aristanetworks/ansible-cvp/blob/master/docs/cv_facts.md) or [Wiki page](https://github.com/aristanetworks/ansible-cvp/wiki/Modules-Documentation#collect-facts-from-cloudvision)
