### ISSUE TITLE
When root container is not Tenant, cv_container fails

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#113]
Issue Type
------

 - Bug Report
 

Module Name
------

cv_container

Description
------

Module assumes root container is always named `Tenant` as it is the default value. But some design have this value changed.

When root container is not Tenant then, module starts an infinite loop as it is looking for a non-existing key. 

Instead of assuming root is Tenant, module should identify the root container and use it as base for the tree representation

**Comment by titom73** [comment]
Need to remove references to `Tenant` in default container as well:

```python
modules/cv_container.py:    default_containers = ['Tenant', 'Undefined', 'root']
```

**Comment by titom73** [comment]
Dynamic root container identification tested in lab sucessfuly:

```
2020-01-10 10:19:16,240   -> CloudVision container {'Key': 'root', 'Name': 'Tenant', 
'CreatedBy': 'cvp system', 'CreatedOn': 1569850167062, 'Mode': 'expand', 'name': 'Tenant',
'key': 'root', 'parentName': None, 'parentId': None, 'type': None, 'id': 21,
'factoryId': 1, 'userId': None, 'childContainerId': None, 'devices': [], 'configlets': [],
'imageBundle': ''}
2020-01-10 10:19:16,240   -> CloudVision ROOT container has name Tenant
```

Must be tested in a setup with custom root container

**Comment by Hugh-Adams** [comment]
Thanks Thomas,

I'll test it today and confirm

Best Regards
Hugh

**Comment by titom73** [comment]
Tested with following scenario:

- Standard setup with Tenant as root (small playbook)
- Custom setup with User defined name for root
- Standard with AVD (large playbook)
