### ISSUE TITLE
Feature Request - Implement diff for cv_configlet, and set changed to true even in check mode

### ISSUE THREAD

**Issue by b-abadie** [aristanetworks/ansible-cvp#120]
`cv_configlet` should, when changing a configlet's content, return a diff to Ansible.

Also, to mirror other standard modules' behavior, it should set `changed=True` in check mode when changes would have been made. This seems logical to me, to prevent the operator from running a playbook (after having performed a dry-run beforehand) thinking some steps will not change anything. 

PR incoming.

**Comment by titom73** [comment]
Covered by PR #121
