### ISSUE TITLE
https error for cv.facts

### ISSUE THREAD

**Issue by mahmutaydin1** [aristanetworks/ansible-cvp#163]

**Comment by titom73** [comment]
Hello @mahmutaydin1 

Could you please elaborate more ? 
Without more information, we won't be able to investigate.

**Comment by mahmutaydin1** [comment]
Hi,

Sorry. Actually my problem is  as below.

*I  am  trying to   integrate CVP and ansble and testing some modules. I
have started with getting factsc from CVP.*



This is hosts file

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[cvp]



172.16.91.3



[cvp:vars]

ansible_host= 172.16.91.3

ansible_httpapi_host= 172.16.91.3

ansible_user='cvpadmin'

ansible_password='arista'

ansible_connection=httpapi

ansible_httpapi_use_ssl=yes

ansible_httpapi_validate_certs=no

ansible_network_os=eos

ansible_httpapi_port=443

# Configuration to get Virtual Env information

ansible_python_interpreter=$(which python)

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx



this is playbook file:

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

---

- name: Build Switch Config

  hosts: cvp

  connection: local

  gather_facts: no





  tasks:

    - name: "collecting facts from CVP {{inventory_hostname}}"

      arista.cvp.cv_facts:

        facts:

          containers

    - name: "Print out facts from CVP"

      debug:

        msg: "{{containers}}"

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx



*My purpose is getting only containers name  that exists in CVP.When I run
my playbook, I am receving  below output. *

*Could you please help me to edit playbook for debug  statement? I want
only see name of each containers not another value of  list.*



*Thank you so much*





[root@centos7 ansible]# ansible-playbook test_facts.yml



[root@centos7 ansible]# ansible-playbook test_facts.yml

PLAY [Build Switch Config]
**************************************************************************************************************************************************************************************************************

TASK [collecting facts from CVP 172.16.91.3]
********************************************************************************************************************************************************************************************
ok: [172.16.91.3]

TASK [Print out facts from CVP]
*********************************************************************************************************************************************************************************************************
ok: [172.16.91.3] => {
    "msg": [
        {
            "CreatedBy": "cvp system",
            "CreatedOn": 1579652551582,
            "Key": "root",
            "Mode": "expand",
            "Name": "Tenant",
            "childContainerId": null,
            "configlets": [],
            "devices": [],
            "factoryId": 1,
            "id": 21,
            "imageBundle": "",
            "key": "root",
            "name": "Tenant",
            "parentId": null,
            "parentName": null,
            "type": null,
            "userId": null
        },
        {
            "CreatedBy": "cvpadmin",
            "CreatedOn": 1579686077097,
            "Key": "container_1_34356809282151",
            "Mode": "expand",
            "Name": "Spine",
            "childContainerId": null,
            "configlets": [
                "Mahmut_Leaf_Initial",
                "SYS_TelemetryBuilderV2",
                "Mahmut_Spine_Builder"
            ],
            "devices": [
                "SPINE-1",
                "SPINE-2"
            ],
            "factoryId": 1,
            "id": 21,
            "imageBundle": "vEOS-lab-4.22.3M",
            "key": "container_1_34356809282151",
            "name": "Spine",
            "parentId": "root",
            "parentName": "Tenant",
            "type": null,
            "userId": null
        },
        {
            "CreatedBy": "cvpadmin",
            "CreatedOn": 1579686092946,
            "Key": "container_3_34372658384735",
            "Mode": "expand",
            "Name": "Leaf",
            "childContainerId": null,
            "configlets": [
                "Mahmut_Leaf_Initial",
                "SYS_TelemetryBuilderV3",
                "Mahmut_Leaf_Builder"
            ],
            "devices": [
                "LEAF-1",
                "LEAF-2",
                "LEAF-3",
                "LEAF-4"
            ],
            "factoryId": 1,
            "id": 21,
            "imageBundle": "vEOS-lab-4.22.3M",
            "key": "container_3_34372658384735",
            "name": "Leaf",
            "parentId": "root",
            "parentName": "Tenant",
            "type": null,
            "userId": null
        },
        {
            "CreatedBy": "cvpadmin",
            "CreatedOn": 1581160310501,
            "Key": "container_132_5895992835588",
            "Mode": "expand",
            "Name": "Internet",
            "childContainerId": null,
            "configlets": [
                "Mahmut_Leaf_Initial",
                "SYS_TelemetryBuilderV2",
                "Mahmut_Internet_Builderv2"
            ],
            "devices": [
                "INTERNET-5",
                "INTERNET-6"
            ],
            "factoryId": 1,
            "id": 21,
            "imageBundle": "vEOS-lab-4.22.3M",
            "key": "container_132_5895992835588",
            "name": "Internet",
            "parentId": "root",
            "parentName": "Tenant",
            "type": null,
            "userId": null
        },
        {
            "CreatedBy": "cvp system",
            "CreatedOn": 1579652551614,
            "Key": "undefined_container",
            "Mode": "expand",
            "Name": "Undefined",
            "childContainerId": null,
            "configlets": [],
            "devices": [
                "sw-172.16.91.63.netsys.lab",
                "sw-172.16.91.64.netsys.lab"
            ],
            "factoryId": 1,
            "id": 21,
            "imageBundle": "EOS-4.20.14M",
            "key": "undefined_container",
            "name": "Undefined",
            "parentId": "root",
            "parentName": "Tenant",
            "type": null,
            "userId": null
        }
    ]
}

PLAY RECAP
******************************************************************************************************************************************************************************************************************************
172.16.91.3                : ok=2    changed=0    unreachable=0    failed=0
   skipped=0    rescued=0    ignored=0

Thomas Grimonet <notifications@github.com>, 19 Mar 2020 Per, 23:38
tarihinde şunu yazdı:

**Comment by titom73** [comment]
Hello,

On behalf of @noredistribution 

You should use `loop_control`

```yaml
--- 
- name: Build Switch Config 
  hosts: CVP 
  connection: local 
  gather_facts: no 
  tasks: 
    - name: "collecting facts from CVP {{inventory_hostname}}" 
      arista.cvp.cv_facts: 
        facts: 
          containers 
    - name: "Print out facts from CVP" 
      debug: 
        msg: "{{item.name}}" 
      with_items: "{{containers}}" 
      loop_control: 
        label: '{{ item.name }}' 
```

And the result is:

```shell
ansible-playbook test.yaml -i inv2.yaml                                                                              

PLAY [Build Switch Config] ***********************

TASK [collecting facts from CVP cloudvision] ***********************
ok: [cloudvision] 

TASK [Print out facts from CVP] 
ok: [cloudvision] => (item=Tenant) => { 
    "msg": "Tenant" 
} 
ok: [cloudvision] => (item=Kishore-Test) => { 
    "msg": "Kishore-Test" 
} 
ok: [cloudvision] => (item=Guillaume) => { 
    "msg": "Guillaume" 
} 
ok: [cloudvision] => (item=PTP) => { 
    "msg": "PTP" 
} 
ok: [cloudvision] => (item=for punit) => { 
    "msg": "for punit" 
} 
ok: [cloudvision] => (item=runxin_test2) => { 
    "msg": "runxin_test2" 
} 
ok: [cloudvision] => (item=Ronie) => { 
    "msg": "Ronie" 
} 
ok: [cloudvision] => (item=SpinesR) => { 
    "msg": "SpinesR" 
} 
ok: [cloudvision] => (item=LeavesR) => { 
    "msg": "LeavesR" 
} 
ok: [cloudvision] => (item=DC1_FABRIC) => { 
    "msg": "DC1_FABRIC" 
} 
ok: [cloudvision] => (item=DC1_LEAFS) => { 
    "msg": "DC1_LEAFS" 
} 
ok: [cloudvision] => (item=DC1_LEAF1) => { 
    "msg": "DC1_LEAF1" 
} 
ok: [cloudvision] => (item=DC1_LEAF2) => { 
    "msg": "DC1_LEAF2" 
} 
ok: [cloudvision] => (item=DC1_SPINES) => { 
    "msg": "DC1_SPINES" 
} 
ok: [cloudvision] => (item=Undefined) => { 
    "msg": "Undefined" 
}
```

**Comment by mahmutaydin1** [comment]
Thank you so much

20 Mart 2020 Cuma tarihinde Thomas Grimonet <notifications@github.com>
yazdı:
