### ISSUE TITLE
Mode:"delete" is not working in cv_container module

### ISSUE THREAD

**Issue by mahmutaydin1** [aristanetworks/ansible-cvp#167]
## Summary

I am ısing cv_contaniner module. The parameter "mode" is working when value is merge. However it does not work  when it is delete. I am receving below error.

Could you please help me?

## Role or Module Name
__Module name:__ `cv_container`

---
- name: Build First CVP Config
  hosts: cvp
  connection: local
  gather_facts: no
  collections:
    - arista.cvp

  vars:
    containers_provision:
      Istanbul:
        parent_container: Tenant
      Ankara:
        parent_container: Tenant
      Istanbul-Spines:
        parent_container: Istanbul
      Istanbul-Leafs:
        parent_container: Istanbul
      Istanbul-Leaf-A:
        parent_container: Istanbul-Leafs
      Istanbul-Leaf-B:
        parent_container: Istanbul-Leafs

      Ankara-Spines:
        parent_container: Ankara
      Ankara-Leafs:
        parent_container: Ankara
      Ankara-Leaf-A:
        parent_container: Ankara-Leafs
      Ankara-Leaf-B:
        parent_container: Ankara-Leafs

  tasks:
    - name: "collecting facts from CVP {{inventory_hostname}}"
      arista.cvp.cv_facts:
        facts:
          containers,configlets

      register: facts

    - name: "Print out facts from CVP"
      vars:
        configlets: "{{item.configlets}}"
        devices: "{{item.devices}}"

      debug:
        msg:

          - "PARENT CONTAINER NAME is : {{item.parentName}}"
          - "CONTAINER NAME is : {{item.name}}"
          - "IT HAS BELOW CONTAINER_CONFIGLETS :"
          - "{{configlets}}"
          - "THIS CONTAINER HAS IMAGE: {{item.imageBundle}}"
          - "THIS CONTAINER HAS BELOW DEVICES:"
          - "{{devices}}"

      with_items: "{{containers}}"

      loop_control:
        label: "{item.name}}"

    - name: "Creating Container Topology on {{inventory_hostname}}"
      cv_container:
        topology: "{{containers_provision}}"
        cvp_facts: "{{facts.ansible_facts}}"
        mode: delete
TASK [Creating Container Topology on 172.16.91.3] ***************************************************************************************************************************************************************************************
fatal: [172.16.91.3]: FAILED! => {"changed": false, "module_stderr": "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.91.3'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\n/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.91.3'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-20513tbkzlH/ansible-tmp-1585041715.39-245151660489282/AnsiballZ_cv_container.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-20513tbkzlH/ansible-tmp-1585041715.39-245151660489282/AnsiballZ_cv_container.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-20513tbkzlH/ansible-tmp-1585041715.39-245151660489282/AnsiballZ_cv_container.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.arista.cvp.plugins.modules.cv_container', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_cv_container_payload_bSmBwA/ansible_cv_container_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_container.py\", line 1092, in <module>\n  File \"/tmp/ansible_cv_container_payload_bSmBwA/ansible_cv_container_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_container.py\", line 1075, in main\n  File \"/tmp/ansible_cv_container_payload_bSmBwA/ansible_cv_container_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_container.py\", line 934, in delete_topology\n  File \"/tmp/ansible_cv_container_payload_bSmBwA/ansible_cv_container_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_container.py\", line 543, in is_empty\nKeyError: 'devices'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *******

**Comment by mahmutaydin1** [comment]
Addition to my problem; when I update my var: parametr for only one container (most inner container), my playbook is stucking  on below setup for a long time.


TASK [Creating Container Topology on 172.16.91.3] ***************************************************************************************************************************************************************************************

**Comment by noredistribution** [comment]
As we discussed, you're initial error was because you didn't collect the facts about the devices. A container can only be deleted with no devices attached to it. Changing the playbook to reflect the same will fix the problem

```
arista.cvp.cv_facts:
  facts:
   containers,configlets,devices
```

or removing the facts

```
arista.cvp.cv_facts:
```

For the other problem I'll open another issue, currently deleting containers only work if the container  is a child of the  root container ( Tenant ) or in case of nested containers if you delete the whole tree
