### ISSUE TITLE
HTTP fallback causes 'Invalid Credentials' error to be masqueraded as 'Bad Request'  

### ISSUE THREAD

**Issue by b-abadie** [aristanetworks/ansible-cvp#183]
## Issue Type

- [x] Bug fix (non-breaking change which fixes an issue)

## Summary

When explicitly specifying an HTTPS port number, automatic fallback to HTTP in `cv_client.py` line 303 causes an 'Invalid Credentials' error to be presented as 'Bad Request' to the user, due to an attempt to perform an HTTP request on an HTTPS port.

Note that this is probably the case for more errors, namely all exceptions raised line 328 : 
```
        except (ConnectionError, CvpApiError, CvpRequestError,
                CvpSessionLogOutError, HTTPError, ReadTimeout, Timeout,
                TooManyRedirects) as error:
```

## Role or Module Name

__Module name:__ `cv_client`

`arista.cvp` collection and Python libraries version 1.0.6

## OS / Environment

__Cloudvision version__

2018 and 2019

## Steps to reproduce

```yaml
- name: Get latest configlets from CVP
  arista.cvp.cv_facts:
    facts:
      - configlets
```
With variables :
```
ansible_connection: httpapi
ansible_network_os: eos
ansible_httpapi_use_ssl: True
ansible_httpapi_validate_certs: False
ansible_user: "user"
ansible_password: "notthecorrectpassword"
ansible_httpapi_host: "192.168.122.2"
ansible_host: "443"
ansible_httpapi_port: "443"

```

### Expected results

```shell
TASK [leaf/underlay : Get latest configlets from CVP] ***********************************************************************************************************************************************************
fatal: [host-01]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "\n192.168.122.2: Authenticate: https://192.168.122.2:443/web/login/authenticate.do: Request Error: Invalid credentials\n"}
```

### Actual results

```shell
TASK [leaf/underlay : Get latest configlets from CVP] ***********************************************************************************************************************************************************
fatal: [host-01]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "\n192.168.122.2: Authenticate: http://192.168.122.2:443/web/login/authenticate.do: Request Error: Bad Request\n"}

```
Note the HTTP vs HTTPS on port 443.

The expected result was actually obtained running code from this branch : https://github.com/aristanetworks/ansible-cvp/compare/master...b-abadie:fix-bad-requests
But this is not PR-worthy material. In fact I am not quite sure how to fix, this is why I am only submitting an issue and not a PR.

**Comment by titom73** [comment]
- PR #185 to __`releases/v1.1.x`__
- Cherry picked to __`releases/v1.0.x`__
