### ISSUE TITLE
ansible_httpapi_validate_certs is ignored

### ISSUE THREAD

**Issue by freedge** [aristanetworks/ansible-cvp#238]
## Summary

There are multiple issues with the way ansible-cvp module establishes a trusted SSL connection to the cvp server:

- first because of issue described in https://github.com/aristanetworks/cvprac/pull/123 , cvprac client will sometimes fallback to http and sends credentials in clear text over the network
- cvprac actually provides a way to verify the identity of the server (avoiding the trap above), but this seems unused by the ansible-cvp module. Even when setting ansible_httpapi_validate_certs=True, the connection is established without verification, and the credentials sent to the server.

Thanks for your help

**Comment by titom73** [comment]
Hi @freedge 

Thank you for your feedback. I will look at how we can add support for cert validation.

Regards,

**Comment by titom73** [comment]
Hello @freedge 

A PR is in progress to support `ansible_httpapi_validate_certs` option available with HTTPAPI. 

It currently works only with valid SSL certificate and does not support self-signed or signed by a private CA not installed in Python.

Support for self-signed is still under investigation as we need to get a correct vehicule to get path to CRT to pass like `validate_certs`

**Comment by freedge** [comment]
thanks! in the end if it works by putting the cert  under certs/ folder, running c_rehash certs, and export SSL_CERT_DIR=certs, it's perfect

EDIT: well above did not work sadly. A workaround, that works in my virtualenv is

```
cat cert.pem >> `python -m certifi`
```

In any case, I verified that the certificate is now validated with the change you propose. I think you can close the issue with the merge.

**Comment by titom73** [comment]
Thanks for your feedback.

We will do some additional testing and update the documentation accordingly and we will merge this PR later.
