### ISSUE TITLE
Feature Request - To support assigning topology tag with new CVP resource API

### ISSUE THREAD

**Issue by slackwei** [aristanetworks/ansible-cvp#281]
## Request Type

- [X] New feature (non-breaking change which adds functionality)

## Detailed Description
With CVP 2020.2.3, device topology tag is supported with new resource API 
https://github.com/aristanetworks/cloudvision-apis
This help to build up topology accurately based on DC/POD/RACK informatioin

## Context
To get to the end goal, it will require the following:
1. A foundational module will need to be created to take advantage of the new API.
2. Once completed, we will also need to extend AVD with a specific cvp_topology_tag role.

**Comment by carlbuchmann** [comment]
On hold - wait for new resource APIs which will come in CVP 2020.4.0

**Comment by ClausHolbechArista** [comment]
Please implement this with support for all exposed tag types.

**Comment by noredistribution** [comment]
the resource APis have been added to cvprac a while ago, example can be found here: https://github.com/aristanetworks/cvprac/blob/develop/docs/labs/lab08-resource-apis/topology_tag_assignment.py
