### ISSUE TITLE
Update cvprac token field for CV authentication

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#283]
## Issue Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation Report
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Other (please describe):

## Summary

Since `cvrac` is going to deprecate `cvaas_token` in regards to `api_token`, collection backend shall be updated accordingly.

Reference: https://github.com/aristanetworks/cvprac/pull/127

**Comment by guillaumeVilar** [comment]
The `api_token` variable is not yet available in cvprac version 1.0.4.
For now, this variable is only available in the `devel` cvprac branch. 
I guess we will need to wait until a new cvprac version is available in order to implement this change.

**Comment by titom73** [comment]
Also service account is still in beta on Cloudvision side.
