### ISSUE TITLE
Feature Request -Provision devices based on Serial Number instead of Hostname

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-cvp#297]
## Request Type

- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (please describe):

## Detailed Description

**Is your feature request related to a problem? Please describe.**
Allow an option to identify devices based on serial-number instead of hostname for all actions.

## Context

When deploying new devices with ZTP we currently require static DHCP reservations with hostname set for each device. If we could change this module to use serial-number, we would no longer require the static DHCP reservations.

**Comment by titom73** [comment]
Work in progress

- Branch: https://github.com/titom73/ansible-cvp/tree/features/provision-serial
- PR: Not available yet
