### ISSUE TITLE
synchronising-cloudvision-portal-configlets-with-ansible

### ISSUE THREAD

**Issue by pronet1976** [aristanetworks/ansible-cvp#298]
Hello, 
I have some difficulties to sync Ansible to my CVP platform.
Does anyone have an idea of how to fix this configuration?

fatal: [cvp_server]: FAILED! => {"changed": false, "msg": "\ncvp_server: HTTPSConnectionPool(host='cvp_server', port=443): Max retries exceeded with url: /web/login/authenticate.do (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0112990d60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n"}

here is the example taken:

[cvp_servers]
cvp_server ansible_httpapi_host=192.168.85.85

[cvp_servers:vars]
ansible_connection = 'httpapi'
ansible_httpapi_use_ssl = True
ansible_httpapi_validate_certs = False
ansible_user = cvpadmin
ansible_password = Testing1!
ansible_network_os = 'eos'
ansible_httpapi_port = 443
ansible_python_interpreter = /usr/bin/python3

the official arista link here:
https://eos.arista.com/synchronising-cloudvision-portal-configlets-with-ansible/

If you have already test this module, any additional informations interests me.
Thanks,

**Comment by freedge** [comment]
I use it, works great. Try ansible_host instead of ansible_httpapi_host ?

**Comment by pronet1976** [comment]
> I use it, works great. Try ansible_host instead of ansible_httpapi_host ?

I see, it works now thank you.
