### ISSUE TITLE
Could not find or access 'template.shared_configlets.j2

### ISSUE THREAD

**Issue by pronet1976** [aristanetworks/ansible-cvp#299]
Hello,

I'm new to ansible and I have another difficulties to sync Ansible to my CVP platform. 
This time I have error that say like this:

 PLAY [Check Shared Configlets across CVP clusters] *******************************************************************************************

TASK [cvp.sync : collect CVP Facts] **********************************************************************************************************
ok: [cvp_server]

TASK [cvp.sync : Extract shared Configlets] **************************************************************************************************
fatal: [cvp_server -> localhost]: FAILED! => {"changed": false, "msg": "Could not find or access 'template.shared_configlets.j2'\nSearched in:\n\t/etc/ansible/Ansible_Sand_Pit/roles/cvp.sync/templates/template.shared_configlets.j2\n\t/etc/ansible/Ansible_Sand_Pit/roles/cvp.sync/template.shared_configlets.j2\n\t/etc/ansible/Ansible_Sand_Pit/roles/cvp.sync/tasks/templates/template.shared_configlets.j2\n\t/etc/ansible/Ansible_Sand_Pit/roles/cvp.sync/tasks/template.shared_configlets.j2\n\t/etc/ansible/Ansible_Sand_Pit/templates/template.shared_configlets.j2\n\t/etc/ansible/Ansible_Sand_Pit/template.shared_configlets.j2 on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

PLAY RECAP ***********************************************************************************************************************************
cvp_server                 : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

the example I take:

[cvp_servers]
cvp_server ansible_host=192.168.85.85

[cvp_servers:vars]
ansible_connection = 'httpapi'
ansible_httpapi_use_ssl = True
become = True
ansible_httpapi_validate_certs = False
ansible_user = cvpadmin
ansible_password = Testing1!
ansible_network_os = 'eos'
ansible_httpapi_port = 443
ansible_python_interpreter = /usr/bin/python3

the official arista link here:
https://eos.arista.com/synchronising-cloudvision-portal-configlets-with-ansible/

If you have any solution/informations it interests me.
Thanks,

**Comment by titom73** [comment]
Hello @pronet1976 

It seems documentation you followed has incorrect links. Indeed, it refers to an old implementation of synchronisation and outside of this collection.

arista.cvp collection has a dedicated role which does the exact same thing. Documentation is available here: https://cvp.avd.sh/en/latest/roles/configlets_sync/

Please let me know how it goes with this documentation. Besides that, I will reach out to my colleague to fix link.

Kind Regards,

**Comment by pronet1976** [comment]
> Hello @pronet1976
> 
> It seems documentation you followed has incorrect links. Indeed, it refers to an old implementation of synchronisation and outside of this collection.
> 
> arista.cvp collection has a dedicated role which does the exact same thing. Documentation is available here: https://cvp.avd.sh/en/latest/roles/configlets_sync/
> 
> Please let me know how it goes with this documentation. Besides that, I will reach out to my colleague to fix link.
> 
> Kind Regards,

This documentation that you give me is use for synchronize CVP too other CVP which is not wrong, but apparently I realize, what I really need to know is how to synchronize Ansible too Cloud Vision Platform so I can configure my Arista networks Spine and Leaf, through Cloud Vision Platform, with Ansible. demo is in this video: https://youtu.be/lHtXtazgFvQ.

If you have any solution, informations, or documentation can you please let me know.
Thank you.

**Comment by titom73** [comment]
Have you checked out this content as it is what @fredhsu used during his demo: https://github.com/aristanetworks/netdevops-examples/tree/master/demo/ansible-batfish-cv-nfd22
