### ISSUE TITLE
Add fact filter to cv_facts

### ISSUE THREAD

**Issue by networkop** [aristanetworks/ansible-cvp#32]
One more thing that might be useful is to be able to filter what type of facts you want to collect. for example, if you expect only tasks to have changed, then it should be possible to run cv_facts with something like `filter: tasks` to only make it update tasks.

**Comment by titom73** [comment]
Maybe we could track #31 and this one #32 directly part of Issue #30 as a `cv_facts` enhancement change ?

**Comment by networkop** [comment]
yep, sounds good
