### ISSUE TITLE
cv_configlet says filter_mode is unsupported

### ISSUE THREAD

**Issue by ghost** [aristanetworks/ansible-cvp#328]
Whenever i try to update a configurelet i have an issue where i have a similar name,
for example : 
```
hq-sw-f12-user
hq-sw-f12-userB
hq-sw-f12-user-backup
backup-hq-sw-f12-user

```
It is overwriting all of the configuerlets, by your documentation i see i can use filter_mode for this issue to have strict name
so when i change `hq-sw-f12-user `it wont catch all options like `*hq-sw-f12-user*` but more like `linux -w \ -o hq-sw-f12-user`

This is my playbook:
```
---
- name: Playbook to demonstrate cv_container module.
  hosts: cvp_servers
  connection: local
  gather_facts: no
  collections:
    - arista.avd
    - arista.cvp
  vars:
    configlet_list:
            hq-sw-f12-user: "{{lookup('file', 'configlets/GLOBAL-ALIASES.conf')}}"

  vars_files:
            - vars.yml
  tasks:
    - name: "Gather CVP facts from {{inventory_hostname}}"
      arista.cvp.cv_facts:
        facts:
          configlets
      register: cvp_facts

    - name: 'Create configlets on CVP {{inventory_hostname}}.'
      #arista.cvp.cv_configlet:
      cv_configlet:
        cvp_facts: "{{cvp_facts.ansible_facts}}"
        configlets: "{{configlet_list}}"
        state: present
        filter_mode: strict
        configlets_notes: "1Configlet managed by Ansible"
        configlet_filter: ["hq-sw-f12-user"]

      register: cvp_configlet

    - debug:
        msg: '{{cvp_configlet}}'

```
I get this error message:

`    "msg": "Unsupported parameters for (cv_configlet) module: filter_mode Supported parameters include: configlet_filter, configlets, configlets_notes, cvp_facts, state"
`
Using ansible 2.10.7 
Other then that playbook works fine.
ref : https://cvp.avd.sh/en/latest/docs/modules/cv_configlet.rst/

**Comment by titom73** [comment]
Hello @batchenr

This keyword is new and at this time only available if you use this collection from git and not from ansible-galaxy. It is going to be part of v2.1.2 release I am working on. (PR #327)

**Comment by ghost** [comment]
For some reason it does work now, after installed like this :
`ansible-galaxy collection install arista.avd arista.cvp`
doesn't give error anymore.

**Comment by titom73** [comment]
Version has been released yesterday evening EMEA time. So with your last command, you have taken v2.1.2 with this new option.

Regards,
