### ISSUE TITLE
Create makefiles for common tasks like testing, linting

### ISSUE THREAD

**Issue by networkop** [aristanetworks/ansible-cvp#34]
It would be handy to have a makefile that would run tests, lint and execute test playbooks against our lab both for personal dev and ci/cd pipelines.

**Comment by titom73** [comment]
Basic version for `examples` folder available via PR #46

**Comment by titom73** [comment]
During investigation about how to test / lint / and cleanup, [molecule](https://molecule.readthedocs.io/en/stable/) comes to the top of the list as we are building ansible content.

Here is a [first feedback](https://www.jeffgeerling.com/blog/2019/how-add-integration-tests-ansible-collection-molecule) about how to use modulecule with ansible collection

Have you played with it already ?

**Comment by networkop** [comment]
i don't think we'd be able to do much with molecule. it's good for stuff like "install nginx, configure nginx, check that port 80 is opened". In our case, we can't mock CVP so doing localised tests is difficult.
I was thinking more along the lines of ansible-lint for linting and pre-canned makefile targets for testing, e.g. `make test-tasks` will trigger a `ansible-playbook -i inventory.ini playbook.tasks.yaml`. So stuff that will make it easier to re-run tests without having remember the exact command syntax.

**Comment by titom73** [comment]
It makes definitely sense. Let's implement a Makefile for linting and validation tests.
