### ISSUE TITLE
Support Configlet Order Updates

### ISSUE THREAD

**Issue by cdorryarista** [aristanetworks/ansible-cvp#362]
## Request Type

- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (please describe):

## Detailed Description
Working with customer that is looking to deploy with ansible cvp, and they are looking at the following scenario.  We have device Leaf1 and the initial build is the following configlets.

config1
config2
config4
config5

When they go back and see they forgot config3, if the update the playbook for cv_device, they order the configlets as below:
config1
config2
config3
config4
config5

However, after the push the configlet order isn't as its defined in the vars file instead config 3 was appended to the end:
config1
config2
config4
config5
config3

## Context
This would enable updates and adding configlets in a specific order, as they have some configlets that are setting "default" values, and need those defaults to come before the more specific settings

## Possible Implementation

Not sure if its possible to remove and then re-add the configlets which will ensure proper ordering or if there's a better way which the dev team can discover.

**Describe alternatives you've considered**

**Comment by quulah** [comment]
I'm looking to do something similar, but with a slight twist.

I have Ansible setting base configlets, which should always be the first one. Then with `apply_mode: loose` allow the users to create configlets manually for testing purposes through CVP.

The ordering matters, so it would be great to have control over that through the module.

**Comment by guillaumeVilar** [comment]
Hello, thanks for the inputs. 
We are looking into adding a new function in cvprac (https://github.com/aristanetworks/cvprac) in order to deal with the re-ordering of the configlets. This will require some investigations.

Our plan would be to respect the configlets order specified in loose and strict mode.

I believe that will solve both requirements.
