### ISSUE TITLE
configlets_notes for cv_configlet_v3 using CVP 2021.1.0

### ISSUE THREAD

**Issue by gmoisio** [aristanetworks/ansible-cvp#371]
Hi all, using configlets_notes for cv_configlet_v3, it looks like the note default message from configlet_tools.py ('Managed by Ansible AVD') is always applied.
Thanks
Regards

**Comment by ksator** [comment]
This feature was introduced with [this change](https://github.com/aristanetworks/ansible-cvp/pull/186/commits/c15a4002428e2f3868d970bc5d9f35f88601033b) with the addition of the variable `configlets_notes` in the module [cv_configlet.py](https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/modules/cv_configlet.py)   
```
configlets_notes = str(module.params['configlets_notes'])
```
The module [cv_configlet.py](https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/modules/cv_configlet.py) uses  the variable `configlets_notes` in the function `add_note_to_configlet`.   
The function `add_note_to_configlet` is defined in [cvprac](https://github.com/aristanetworks/cvprac/blob/develop/cvprac/cvp_api.py)

**Comment by ksator** [comment]
The module [cv_configlet_v3.py](https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/modules/cv_configlet_v3.py)  uses the variable  `configlets_notes`     
```
configlets_notes=dict(type='str',  default='Managed by Ansible', required=False))
```

The module [cv_configlet_v3.py](https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/modules/cv_configlet_v3.py) imports code from [module_utils/configlet_tools.py ](https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/module_utils/configlet_tools.py)  
```from ansible_collections.arista.cvp.plugins.module_utils.configlet_tools import ConfigletInput, CvConfigletTools```

The [module_utils/configlet_tools.py](https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/module_utils/configlet_tools.py) uses 
```
...
configlets_notes = note
...
def create(self, to_create, note: str = 'Managed by Ansible AVD'):
...
def update(self, to_update: list, note: str = 'Managed by Ansible AVD'):
...
```

The [module_utils/configlet_tools.py](https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/module_utils/configlet_tools.py) uses the variable `configlets_notes` in  the function `add_note_to_configlet` from  [cvprac](https://github.com/aristanetworks/cvprac/blob/develop/cvprac/cvp_api.py)

**Comment by ksator** [comment]
Hello @gmoisio, 
I did not yet test this feature with [cv_configlet_v3.py](https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/modules/cv_configlet_v3.py).  
But I dont see where the value of the variable `configlets_notes` is passed in the module [cv_configlet_v3.py](https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/modules/cv_configlet_v3.py).  
So I suspect this is why the variable `configlets_notes` always uses it's default value (`Managed by Ansible`) ...   
i.e something like this ```configlets_notes = str(module.params['configlets_notes'])``` should be added to [cv_configlet_v3.py](https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/modules/cv_configlet_v3.py)

**Comment by gmoisio** [comment]
Thank you Khelil to take it into account.

**Comment by titom73** [comment]
`configlets_note` var is not propagated through cv_configlet_v3 and hence, function rely on default value set per function (`create` and `update`)

A PR is comming this week to fix this issue.
