### ISSUE TITLE
plugins/module_utils/device_tools.py apply_configlets() is not returning anything when no changes are required

### ISSUE THREAD

**Issue by guillaumeVilar** [aristanetworks/ansible-cvp#409]
### Issue Summary

The following test in the test suite is failing: 
`FAILED system/test_cv_device_tools.py::TestCvDeviceTools::test_configlet_apply[CV_DEVICE0] - IndexError: list index out of range `

When using the function (in plugins/module_utils/device_tools.py) `apply_configlets()` the function is not returning anything when there is no changes to be made. This happens when the lists of configlets before change is the same as the list of configlet after changes. 

We should return a success error message so the test succeed and we can continue to test this function consistently. 

### Which component(s) of AVD impacted

cv_device_v3

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Input variables

```yaml
In `constants_data.py`: 


USER_CONTAINERS = [
    {"PYTEST": {"parentContainerName": "Tenant"}, "Leafs": {"parentContainerName": "PYTEST"}, "Spines": {
        "parentContainerName": "PYTEST", "configlets": ["01TRAINING-01"]}, "POD01": {"parentContainerName": "Leafs"}},
    {"DC-2": {"parentContainerName": "Tenant"}, "DC_Leafs": {
        "parentContainerName": "DC-2"}}
]

CV_CONTAINERS_NAME_ID_LIST = [{"name": "Tenant", "id": "root"}]

STATIC_CONFIGLET_NAME = ["01TRAINING-01"]

TOPOLOGY_STATE = ["present", "absent"]

ANSIBLE_CV_SEARCH_MODE = "hostname"
# IS_HOSTNAME_SEARCH = True

CVP_DEVICES = [
    {
        "fqdn": "gigi-DC1-SPINE1.ire.aristanetworks.com",
        "serialNumber": "6124E5932E947832A47A223D38FFBB87",
        "systemMacAddress": "50:02:00:fe:b0:5d",
        "parentContainerName": "gigi-test",
        "configlets": [
                "01TRAINING-01",
                "RECONCILE_SPINE1"
        ],
    }
]
```
```


### Steps to reproduce

```shell
Run test suit:
cd tests
python3 -m pytest  system/test_cv_device_tools.py
```

### Relevant log output

```shell
FAILED system/test_cv_device_tools.py::TestCvDeviceTools::test_configlet_apply[CV_DEVICE0] - IndexError: list index out of range
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by titom73** [comment]
Related to PR #405
