### ISSUE TITLE
Include gRPC client in Ansible CVP collection

### ISSUE THREAD

**Issue by jmilikien** [aristanetworks/ansible-cvp#472]
### Enhancement summary

Telemetry state data is only accessible via gRPC but there are no gRPC clients in Ansible modules. This request is to include the CloudVision-python library in order to use the gRPC client to collect telemetry data from CVP.

### Which component of AVD is impacted

other

### Use case example

Using CloudVision-python as an Ansible module

### Describe the solution you'd like

Include CloudVision-python within Ansible-cvp collection

### Describe alternatives you've considered

Enabling cvgnmi in terminattr and enabling openconfig on CVP but don't want to add additional load to TerminAttr or CVP.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sugetha24** [comment]
Right now, ansible-cvp only caters to the provisioning part of CVP. What is the usecase for needing to collect telemetry via the ansible-cvp module?
