### ISSUE TITLE
Deprecation Warning for distutils for Python 3.12

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-cvp#477]
When running pytest the following deprecation warning is raised because of the following import: https://github.com/aristanetworks/ansible-cvp/blob/devel/tests/lib/config.py#L7. 

The migration advice is the following: https://peps.python.org/pep-0632/#migration-advice - reimplementing `strtobool`.

cf: https://github.com/python/cpython/blob/main/Lib/distutils/util.py#L308

**Comment by ClausHolbechArista** [comment]
Does not seem like an overwhelming function to implement ourselves :)
