### ISSUE TITLE
Allow for a more granular approach to idempotence

### ISSUE THREAD

**Issue by b-abadie** [aristanetworks/ansible-cvp#49]
Hello,

I am integrating `ansible-cvp`'s modules for a mutual customer of ours and have a request : is it possible to have a more granular approach to the idempotence concept ?
In the current approach with fully idempotent modules, we have to feed them a full topology of containers, devices, images and configlets. They would then proceed and add or modify what needs to be added or modified, but also delete what is found on CVP and not in the topology.

While I like this approach and see the value in it, it causes some issues with the workflow/use-case I am currently implementing.

In particular, I see two topics where it is the case : 

cv_container and device deletion
----------------------

My use case requires to have all switches in the Ansible inventory, each with its group vars and host vars that will ultimately be used to build the final config, while using CVP to bootstrap and configure them. It also requires to leverage the `--limit` feature of Ansible to only affect a subset of the switches at a time (for slow release and redundancy considerations).

This is currently achieved by having two plays : the first one targeting the switches to compute all the necessary vars without actually making any outgoing connection, and the second one targeting CVP to actually create containers and move devices around.

With the current fully idempotent approach, having the playbook executed on two separate sets of switches would have the second pass delete the result of the first one. I know I could build a complete list of devices with the inventory, but that would defeat the point of the `--limit` option. Also, some devices way be configured in the inventory but not booted yet.

My request is to have an option to `cv_container` that would prevent the deletion or move of a device that is in CVP but not in the topology. Another possibility is to have cv_container only create empty containers and have a parameter `container:` to `cv_device`.

I know it looks like a setback from the "full idempotence" model, but here is my rationale : in a classic use of Ansible, if I remove a server from the inventory, Ansible will not do any cleanup, VM deletion or bare metal poweroff. Yet this is acceptable.

cv_device and configlet deletion
----------------------

In the same way, CVP assigns configlets to devices. I'd like to be able to add and edit only a subset of the configlets applied to a particular switch without changing or deleting the others.

The idea behind this is that if I have a playbook to configure a switch's VNIs, I would not want it to touch the underlay or AAA config, no matter what. This is similar to having a playbook configure Apache's virtual hosts that would uninstall an unrelated package, change the allowed SSH keys or upgrade the kernel.

In the end, it is only a matter of how you consider CVP : as a central point that always describes the complete infrastructure (device list, full config and EOS versions), or as a proxy to access EOS switches (and add a whole lot of cool features, I know).

The point of my request for "granular idempotence" is to let the user choose between the two viewpoints, with some modules parameters of something.
Or, even better, have the best of the two : in my workflow I plan on also using the modules with the full topology, in forced dry-run, to hunt for lost devices or rogue config.

**Comment by titom73** [comment]
# cv_container and device deletion

- Issue #58 for implementing `mode` for `cv_container`
- Issue #59 for implementing `filter` for `cv_container`

**Comment by titom73** [comment]
Merge mode for configlet management in `cv_device` supported from issue #117

Closing issue
