### ISSUE TITLE
Missing documentation on how to assign tags

### ISSUE THREAD

**Issue by sebastianw** [aristanetworks/ansible-cvp#498]
### Enhancement summary

The `cv_tag_v3` module is missing documentation on how to assign/unassign tags from devices. Currently it only shows how to create tags on CVP.

### Which component of AVD is impacted

other

### Use case example

I want to assign tags to devices.

### Describe the solution you'd like

Documentation on how to assign/unassign tags to/from devices.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sugetha24** [comment]
You can refer to [this](https://cvp.avd.sh/en/devel/docs/how-to/v3/cv_tag_v3/#example-of-assigning-device-and-interface-tags) example in the docs for assigning tags to devices. Let me know if you still need assistance.
