### ISSUE TITLE
reset_device method inside device_tools will throw error if reset_device cvprac api call returns None.

### ISSUE THREAD

**Issue by Shivani-chourasiya** [aristanetworks/ansible-cvp#585]
### Issue Summary

In ansible_cvp, the utility method **reset_device() inside module_utils/device_tools.py** will throw error at **line #1794**
https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/module_utils/device_tools.py#L1794
when the cvprac api call for reset_device() returns None at **line #1785** 
https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/module_utils/device_tools.py#L1785

### Which component(s) of AVD impacted

cv_device_v3

### How do you run AVD ?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vibhu-gslab** [comment]
Similar issue has been seen for move_device methods in device_tools#1227 https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/module_utils/device_tools.py#L1227 when the cvprac api call for move_device_to_container() returns None at line #1216 https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/module_utils/device_tools.py#L1216

This issue will only be seen if create_task variable is False at https://github.com/aristanetworks/cvprac/blob/develop/cvprac/cvp_api.py#L1963

**Comment by Shivani-chourasiya** [comment]
PR #572
