### ISSUE TITLE
Wait for change control to finish and report overall status

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-cvp#616]
### Enhancement summary

Currently when using change_control_v3, it is not possible to fetch the status of a change control or wait until it ends and get a status. Would need the ability to trigger a change control, wait until it finishes, and retrieve information about an overall status (success, failed, etc), any relevant error messages and a list of executed tasks with relevant information.

### Which component of AVD is impacted

cv_change_control_v3

### Use case example

When running a CI/CD pipeline that executes a change control in the deploy stage, it is required to follow the change control execution and report a status in the pipeline job, with relevant information in the standard output 

### Describe the solution you'd like

An alternative state flag under change_control_v3 that allows to fetch data about the change control execution, including overall status (running, success, failed, etc) and including the list of tasks and ongoing status per task, with relevant messages about any errors).

This could be used in a pipeline job to follow the change control and report a final status before exiting the pipeline job.

This kind of solution would require a loop in the playbook to check periodically until the change control finishes. An alternative could be a 'wait_for' type of plugin that would be able to wait until a change control reaches an end status, and reports back.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
This will be addressed in `arista.avd.deploy_to_cv`.
