### ISSUE TITLE
Set minimum ansible-core version to 2.15

### ISSUE THREAD

**Issue by sugetha24** [aristanetworks/ansible-cvp#692]
Set minimum ansible-core version to 2.15

Required for Ansible collection certification:

The life cycle for Ansible Automation Platform (AAP) 2.3 is ending soon. On May 31, 2024, AAP 2.3 and by extension, Ansible Core 2.14, will be End of Life (EoL).

After this date, all collections submitted for certification and validation must require Ansible Core 2.15 at minimum in the collection’s “meta/runtime.yml” file. Set the requires_ansible key to “>=2.15.0” to pass certification after the AAP 2.3 EoL date.

**Comment by ClausHolbechArista** [comment]
Solved in #699
